Update do not merge workflow
Rewrite to avoid needing a 3rd party action

diff --git a/.github/workflows/do-not-merge.yml b/.github/workflows/do-not-merge.yml
--- a/.github/workflows/do-not-merge.yml
+++ b/.github/workflows/do-not-merge.yml
@@ -11,12 +11,12 @@ on:
 
 jobs:
   do-not-merge:
+    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
+    name: "Prevent Merging"
     runs-on: ubuntu-latest
     steps:
-      # https://github.com/marketplace/actions/require-labels
-      - name: check labels
-        uses: mheap/github-action-required-labels@v1
-        with:
-          mode: exactly
-          count: 0
-          labels: "do not merge"
+      - name: Check for label
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1
