Update stacked PR workflow
Prevent merging stacked PRs.

Similar to other workflows, check if `stacked PR` label exists and fail the PR if it does.

All PRs should merge into the default branch.

diff --git a/.github/workflows/label-stacked.yml b/.github/workflows/label-stacked.yml
--- a/.github/workflows/label-stacked.yml
+++ b/.github/workflows/label-stacked.yml
@@ -36,3 +36,9 @@ jobs:
         if: env.BASE_BRANCH != env.DEFAULT_BRANCH
         with:
           labels: stacked PR
+      - name: prevent merge
+        if: ${{ contains(github.event.*.labels.*.name, 'stacked PR') }}
+        run: |
+          echo "Pull request is stacked. Failing workflow to prevent merge."
+          echo "Pull requests should only merge into the default branch."
+          exit 1
